spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gamepass
    username: postgres
    password: secretpassword

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

jwt:
  secret: ${JWT_SECRET_KEY}
  issuer: ${JWT_ISSUER}
  expiration:
    hours: ${JWT_EXPIRATION_HOURS}
