spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/gamepass}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:secretpassword}

  jpa:
    hibernate:
      ddl-auto: create-drop
    # show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

jwt:
  secret: ${JWT_SECRET_KEY:1010635266556A587E32D2357538782F413F4428472B4BA250F153675B6B5C75}
  issuer: ${JWT_ISSUER:GamePass App}
  expiration:
    hours: ${JWT_EXPIRATION_HOURS:12}
