spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/gamepass}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:secretpassword}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

jwt:
  secret: ${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5275}
  issuer: ${JWT_ISSUER:GamePass App}
  expiration:
    hours: ${JWT_EXPIRATION_HOURS:12}
