spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gamepass
    username: postgres
    password: secretpassword
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
